const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers}});
const id=()=>crypto.randomUUID();
const allowedTasks=new Set(["generate","edit","understand","ocr","transcribe","translate","summarize","math","safety"]);
function cors(request,env){const origin=request.headers.get("origin")||"";const allowed=String(env.ALLOWED_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean);return allowed.includes(origin)?{"access-control-allow-origin":origin,"vary":"origin","access-control-allow-headers":"authorization,content-type,idempotency-key","access-control-allow-methods":"GET,POST,OPTIONS"}:{}}
function auth(request,env){const value=request.headers.get("authorization")||"";if(env.ENVIRONMENT!=="production"&&!env.AUTH_REQUIRED)return {sub:"development",verified:false};if(!value.startsWith("Bearer ")||request.headers.get("x-uvenaro-verified-sub")==null)return null;return {sub:String(request.headers.get("x-uvenaro-verified-sub")).slice(0,128),verified:true}}
async function body(request){try{return await request.json()}catch{return null}}
const int=(value,fallback=0)=>Number.isSafeInteger(Number(value))?Number(value):fallback;
function chatConfig(env){return {enabled:env.CHAT_EXECUTION_ENABLED==="true",provider:String(env.CHAT_PROVIDER||""),model:String(env.CHAT_MODEL||""),url:String(env.CHAT_PROVIDER_URL||""),maxInputTokens:Math.min(12000,Math.max(1,int(env.CHAT_MAX_INPUT_TOKENS,4000))),maxOutputTokens:Math.min(8000,Math.max(1,int(env.CHAT_MAX_OUTPUT_TOKENS,1000))),timeoutMs:Math.min(120000,Math.max(1000,int(env.CHAT_TIMEOUT_MS,30000))),globalCeiling:int(env.CHAT_GLOBAL_DAILY_COST_MICROUSD,0)}}
function estimateTokens(text){return Math.max(1,Math.ceil(String(text).length/3));}
async function priceFor(env,provider,model){if(!env.DB)return null;return env.DB.prepare("SELECT id,input_microusd_per_million AS inputRate,output_microusd_per_million AS outputRate,credit_value_microusd AS creditValue FROM provider_price_snapshots WHERE provider=? AND model=? AND retired_at IS NULL ORDER BY effective_at DESC LIMIT 1").bind(provider,model).first()}
async function reserveChat(env,user,key,input,cfg){
 if(!env.DB)return {error:json({code:"DATABASE_NOT_CONNECTED"},503)};
 const existing=await env.DB.prepare("SELECT id,status,actual_credits AS actualCredits,actual_cost_microusd AS actualCost FROM usage_reservations WHERE owner_id=? AND idempotency_key=?").bind(user.sub,key).first();
 if(existing)return {error:json({code:existing.status==="settled"?"IDEMPOTENCY_REPLAY":"REQUEST_ALREADY_EXISTS",reservation:existing},409)};
 const price=await priceFor(env,cfg.provider,cfg.model);if(!price)return {error:json({code:"PRICE_SNAPSHOT_REQUIRED"},503)};
 const inputTokens=estimateTokens(input.message);if(inputTokens>cfg.maxInputTokens)return {error:json({code:"INPUT_LIMIT_EXCEEDED"},413)};
 const estimatedCost=Math.ceil(inputTokens*price.inputRate/1e6+cfg.maxOutputTokens*price.outputRate/1e6);
 const estimatedCredits=Math.max(1,Math.ceil(estimatedCost/price.creditValue));
 const account=await env.DB.prepare("SELECT plan_id AS planId,status,included_credits AS included,prepaid_credits AS prepaid,reserved_credits AS reserved,cycle_started_at AS cycleStarts,cycle_ends_at AS cycleEnds FROM billing_accounts WHERE owner_id=?").bind(user.sub).first();
 const limits=await env.DB.prepare("SELECT daily_credit_limit AS dailyLimit,monthly_credit_limit AS monthlyLimit,max_request_cost_microusd AS maxRequest,requests_per_minute AS rpm,blocked_until AS blockedUntil FROM usage_limits WHERE owner_id=?").bind(user.sub).first();
 if(!account||account.status!=="active")return {error:json({code:"ACTIVE_SUBSCRIPTION_REQUIRED"},402)};
 if(!limits||estimatedCost>limits.maxRequest)return {error:json({code:"REQUEST_COST_LIMIT_EXCEEDED"},402)};
 if(limits.blockedUntil&&Date.parse(limits.blockedUntil)>Date.now())return {error:json({code:"USAGE_TEMPORARILY_BLOCKED"},429)};
 if(account.included+account.prepaid-account.reserved<estimatedCredits)return {error:json({code:"INSUFFICIENT_CREDITS",required:estimatedCredits},402)};
 const minute=await env.DB.prepare("SELECT COUNT(*) AS used FROM usage_reservations WHERE owner_id=? AND created_at>=datetime('now','-1 minute')").bind(user.sub).first();
 if(int(minute?.used)>=limits.rpm)return {error:json({code:"RATE_LIMIT_REACHED"},429)};
 const day=await env.DB.prepare("SELECT COALESCE(SUM(actual_credits),0) AS used FROM usage_reservations WHERE owner_id=? AND status='settled' AND created_at>=datetime('now','-1 day')").bind(user.sub).first();
 const month=await env.DB.prepare("SELECT COALESCE(SUM(actual_credits),0) AS used FROM usage_reservations WHERE owner_id=? AND status='settled' AND created_at>=?").bind(user.sub,account.cycleStarts).first();
 if(int(day?.used)+estimatedCredits>limits.dailyLimit||int(month?.used)+estimatedCredits>limits.monthlyLimit)return {error:json({code:"FAIR_USE_LIMIT_REACHED"},429)};
 if(cfg.globalCeiling>0){const global=await env.DB.prepare("SELECT COALESCE(SUM(actual_cost_microusd),0) AS used FROM usage_reservations WHERE status='settled' AND created_at>=datetime('now','-1 day')").first();if(int(global?.used)+estimatedCost>cfg.globalCeiling)return {error:json({code:"GLOBAL_SPEND_CEILING_REACHED"},503)}}
 const reservationId=id(),now=new Date().toISOString();
 const update=await env.DB.prepare("UPDATE billing_accounts SET reserved_credits=reserved_credits+?,updated_at=? WHERE owner_id=? AND status='active' AND included_credits+prepaid_credits-reserved_credits>=?").bind(estimatedCredits,now,user.sub,estimatedCredits).run();
 if(!update.meta?.changes)return {error:json({code:"CREDIT_RESERVATION_CONFLICT"},409)};
 try{await env.DB.batch([
  env.DB.prepare("INSERT INTO usage_reservations (id,owner_id,idempotency_key,feature,estimated_credits,estimated_cost_microusd,status,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(reservationId,user.sub,key,"chat",estimatedCredits,estimatedCost,"reserved",now),
  env.DB.prepare("INSERT INTO usage_ledger (id,owner_id,reservation_id,event_type,credits,cost_microusd,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(id(),user.sub,reservationId,"reserve_included",estimatedCredits,estimatedCost,JSON.stringify({priceSnapshotId:price.id,model:cfg.model}),now)
 ]);}catch(error){await env.DB.prepare("UPDATE billing_accounts SET reserved_credits=MAX(0,reserved_credits-?),updated_at=? WHERE owner_id=?").bind(estimatedCredits,now,user.sub).run();throw error}
 return {reservationId,price,estimatedCredits,estimatedCost,inputTokens};
}
async function releaseChat(env,user,reservation,reason){const now=new Date().toISOString();await env.DB.batch([env.DB.prepare("UPDATE usage_reservations SET status='released',settled_at=? WHERE id=? AND owner_id=? AND status='reserved'").bind(now,reservation.reservationId,user.sub),env.DB.prepare("UPDATE billing_accounts SET reserved_credits=MAX(0,reserved_credits-?),updated_at=? WHERE owner_id=?").bind(reservation.estimatedCredits,now,user.sub),env.DB.prepare("INSERT INTO usage_ledger (id,owner_id,reservation_id,event_type,credits,cost_microusd,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(id(),user.sub,reservation.reservationId,"release",reservation.estimatedCredits,0,JSON.stringify({reason}),now)]);}
async function settleChat(env,user,reservation,output,cfg){const outputTokens=estimateTokens(output),cost=Math.ceil(reservation.inputTokens*reservation.price.inputRate/1e6+outputTokens*reservation.price.outputRate/1e6),credits=Math.max(1,Math.min(reservation.estimatedCredits,Math.ceil(cost/reservation.price.creditValue))),now=new Date().toISOString();const account=await env.DB.prepare("SELECT included_credits AS included FROM billing_accounts WHERE owner_id=?").bind(user.sub).first(),fromIncluded=Math.min(int(account?.included),credits),fromPrepaid=credits-fromIncluded;await env.DB.batch([env.DB.prepare("UPDATE billing_accounts SET included_credits=included_credits-?,prepaid_credits=prepaid_credits-?,reserved_credits=MAX(0,reserved_credits-?),updated_at=? WHERE owner_id=? AND included_credits>=? AND prepaid_credits>=?").bind(fromIncluded,fromPrepaid,reservation.estimatedCredits,now,user.sub,fromIncluded,fromPrepaid),env.DB.prepare("UPDATE usage_reservations SET actual_credits=?,actual_cost_microusd=?,status='settled',settled_at=? WHERE id=? AND owner_id=? AND status='reserved'").bind(credits,cost,now,reservation.reservationId,user.sub),env.DB.prepare("INSERT INTO usage_ledger (id,owner_id,reservation_id,event_type,credits,cost_microusd,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(id(),user.sub,reservation.reservationId,"settle",credits,cost,JSON.stringify({provider:cfg.provider,model:cfg.model,inputTokens:reservation.inputTokens,outputTokens}),now)]);return {credits,cost,inputTokens:reservation.inputTokens,outputTokens};}
async function chatResponse(request,env,user,headers){const cfg=chatConfig(env);if(!cfg.enabled)return json({code:"CHAT_EXECUTION_DISABLED",message:"AI chat is not enabled."},503,headers);if(!user.verified)return json({code:"VERIFIED_IDENTITY_REQUIRED"},401,headers);if(!env.CHAT_PROVIDER_API_KEY||!cfg.url||!cfg.provider||!cfg.model)return json({code:"PROVIDER_NOT_CONFIGURED"},503,headers);const key=request.headers.get("idempotency-key");if(!key||key.length>128)return json({code:"VALID_IDEMPOTENCY_KEY_REQUIRED"},400,headers);const input=await body(request);if(!input||typeof input.message!=="string"||!input.message.trim()||input.message.length>12000)return json({code:"INVALID_MESSAGE"},400,headers);const reservation=await reserveChat(env,user,key,input,cfg);if(reservation.error)return new Response(reservation.error.body,{status:reservation.error.status,headers:{...Object.fromEntries(reservation.error.headers),...headers}});const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),cfg.timeoutMs);try{const upstream=await fetch(cfg.url,{method:"POST",headers:{"authorization":`Bearer ${env.CHAT_PROVIDER_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:cfg.model,input:input.message,max_output_tokens:cfg.maxOutputTokens}),signal:controller.signal});const payload=await upstream.json().catch(()=>({}));if(!upstream.ok)throw new Error("PROVIDER_FAILURE");const output=String(payload.output_text||payload.output||"").slice(0,32000);if(!output)throw new Error("EMPTY_PROVIDER_RESPONSE");const usage=await settleChat(env,user,reservation,output,cfg);return json({id:id(),output,usage:{credits:usage.credits,inputTokens:usage.inputTokens,outputTokens:usage.outputTokens}},200,headers)}catch(error){await releaseChat(env,user,reservation,error.name==="AbortError"?"timeout":"provider_failure");return json({code:error.name==="AbortError"?"PROVIDER_TIMEOUT":"PROVIDER_UNAVAILABLE"},503,headers)}finally{clearTimeout(timer)}}
async function routeModel(input,env){
 const catalog=JSON.parse(env.MODEL_CATALOG_JSON||"[]");const task=String(input?.task||"");if(!allowedTasks.has(task))throw new Error("UNSUPPORTED_TASK");
 const modalities=new Set(input?.modalities||["text"]);const candidates=catalog.filter(m=>m.enabled!==false&&m.tasks?.includes(task)&&[...modalities].every(x=>m.modalities?.includes(x))&&(!input.region||input.region==="auto"||!m.regions||m.regions.includes(input.region))&&(!input.privacy||input.privacy==="standard"||m.privacy?.includes(input.privacy)));
 if(!candidates.length)throw new Error("NO_ROUTE");
 const score=m=>(input.quality==="high"?Number(m.quality||0)*4:Number(m.quality||0)*2)-Number(m.cost||0)*2-Number(m.latency||0)/10000+Number(m.health??1)*5;
 candidates.sort((a,b)=>score(b)-score(a));const primary=candidates[0],fallbacks=candidates.slice(1,1+Math.min(3,Number(input.fallbacks)||2));
 return {routeId:id(),provider:primary.provider,model:primary.model,fallbacks:fallbacks.map(x=>({provider:x.provider,model:x.model})),reason:"capability-policy-health-score",expiresAt:new Date(Date.now()+60000).toISOString(),provenance:{policyVersion:"1.0",candidateCount:candidates.length}};
}
async function createAgent(request,env,user){
 const input=await body(request);if(!input?.objective)return json({code:"INVALID_OBJECTIVE",message:"Objective is required."},400);
 const key=request.headers.get("idempotency-key");if(!key)return json({code:"IDEMPOTENCY_REQUIRED"},400);
 const runId=id(),now=new Date().toISOString(),run={id:runId,owner:user.sub,status:"queued",objective:String(input.objective).slice(0,4000),limits:input.limits||{},policy:input.policy||{},createdAt:now,updatedAt:now};
 if(env.DB)await env.DB.prepare("INSERT INTO agent_runs (id, owner_id, status, objective, payload_json, created_at, updated_at, idempotency_key) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").bind(runId,user.sub,"queued",run.objective,JSON.stringify(input),now,now,key).run();
 if(env.AGENT_QUEUE)await env.AGENT_QUEUE.send({runId,owner:user.sub});
 return json(run,202);
}
async function getRun(runId,env,user){if(!env.DB)return json({code:"DATABASE_NOT_CONNECTED"},503);const row=await env.DB.prepare("SELECT id,status,objective,created_at AS createdAt,updated_at AS updatedAt,error_code AS errorCode FROM agent_runs WHERE id=? AND owner_id=?").bind(runId,user.sub).first();return row?json(row):json({code:"NOT_FOUND"},404)}
async function mutateRun(runId,status,env,user){if(!env.DB)return json({code:"DATABASE_NOT_CONNECTED"},503);const now=new Date().toISOString();const out=await env.DB.prepare("UPDATE agent_runs SET status=?,updated_at=? WHERE id=? AND owner_id=? AND status NOT IN ('completed','failed','cancelled','expired')").bind(status,now,runId,user.sub).run();return json({ok:true,id:runId,status,changed:out.meta?.changes||0},202)}
export default {async fetch(request,env){
 const url=new URL(request.url),headers=cors(request,env);if(request.method==="OPTIONS")return new Response(null,{status:204,headers});
 if(url.pathname==="/v1/health")return json({ok:true,version:"2.0.0",services:{database:Boolean(env.DB),queue:Boolean(env.AGENT_QUEUE),storage:Boolean(env.MEDIA),routing:Boolean(env.MODEL_CATALOG_JSON)}},200,headers);
 const user=auth(request,env);if(!user)return json({code:"UNAUTHORIZED"},401,headers);
 try{
  if(url.pathname==="/v1/ai/routes"&&request.method==="POST")return json(await routeModel(await body(request),env),200,headers);
  if(url.pathname==="/v1/chat/responses"&&request.method==="POST")return chatResponse(request,env,user,headers);
  if(url.pathname==="/v1/agents/runs"&&request.method==="POST")return createAgent(request,env,user);
  let m=url.pathname.match(/^\/v1\/agents\/runs\/([^/]+)$/);if(m&&request.method==="GET")return getRun(decodeURIComponent(m[1]),env,user);
  m=url.pathname.match(/^\/v1\/agents\/runs\/([^/]+)\/cancel$/);if(m&&request.method==="POST")return mutateRun(decodeURIComponent(m[1]),"cancelled",env,user);
  m=url.pathname.match(/^\/v1\/agents\/runs\/([^/]+)\/approvals\/([^/]+)$/);if(m&&request.method==="POST"){const input=await body(request);if(!["approve","deny"].includes(input?.decision))return json({code:"INVALID_DECISION"},400,headers);if(env.DB)await env.DB.prepare("UPDATE agent_approvals SET decision=?,reason=?,decided_at=? WHERE id=? AND run_id=? AND owner_id=? AND decision='pending'").bind(input.decision,String(input.reason||"").slice(0,500),new Date().toISOString(),decodeURIComponent(m[2]),decodeURIComponent(m[1]),user.sub).run();return json({ok:true,decision:input.decision},200,headers)}
  return json({code:"NOT_FOUND"},404,headers);
 }catch(error){return json({code:error.message==="NO_ROUTE"?"NO_ROUTE":"INTERNAL_ERROR",message:error.message==="NO_ROUTE"?"No policy-compliant model is currently available.":"Request could not be completed."},error.message==="NO_ROUTE"?503:500,headers)}
}};
